FROM ruby:3.3.1-slim

ENV APP_HOME=/rails \
    BUNDLE_DEPLOYMENT=1 \
    BUNDLE_PATH=/usr/local/bundle \
    RAILS_ENV=test \
    SECRET_KEY_BASE_DUMMY=dummy

WORKDIR ${APP_HOME}

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    libpq-dev \
    libvips \
    pkg-config \
    postgresql-client \
  && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .
RUN mkdir -p tmp/pids log storage

CMD ["bin/rails", "test"]
